# Generated by Django 4.1.7 on 2026-02-09 06:31

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('section_1', 'Section 1'), ('section_2', 'Section 2'), ('section_3', 'Section 3')], max_length=20)),
                ('image', models.ImageField(upload_to='works/', validators=[website.models.validate_image_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
