# Generated by Django 5.2.9 on 2026-02-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage_testimonial_work_delete_workimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/instagram/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='works/reels/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='works/websites/')),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Works', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='website',
            name='works_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='website.workspage'),
        ),
        migrations.AddField(
            model_name='reel',
            name='works_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='website.workspage'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='works_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='website.workspage'),
        ),
    ]
