# Generated by Django 5.2.9 on 2026-02-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_instagram_reel_website_workspage_delete_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='works_page',
        ),
        migrations.RemoveField(
            model_name='website',
            name='works_page',
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='WorksPage',
        ),
    ]
